modLoader="javafml"
loaderVersion="[1,)"
license="GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007"

[[mods]] #mandatory
    modId="aequivaleo"
    version="${version}"
    displayName="Aequivaleo"
    authors="OrionOnline, LDTTeam"
    description='''
        Mediator mod which allows for high performance analysis of recipes, their inputs and outputs.
    '''
[[dependencies.aequivaleo]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcVersion}"
    ordering="NONE"
    side="BOTH"
[[dependencies.aequivaleo]]
    modId="neoforge" #mandatory
    mandatory=true #mandatory
    versionRange="${forgeVersion}" #mandatory
    ordering="NONE"
    side="BOTH"