configurations {
    implementation.extendsFrom library
}

// All jar files from this folder will be added automatically as runtime mod dependencies
def extraModsDir = "extra-mods-${project.exactMinecraftVersion}"
file(extraModsDir).mkdir()

repositories {
    flatDir {
        name "extra-mods"
        dir file(extraModsDir)
    }
}

dependencies {

    library ("org.jgrapht:jgrapht-core:${project.jgraphtVersion}") {
        exclude group: "org.antlr"
    }
    library ("org.jgrapht:jgrapht-ext:${project.jgraphtVersion}") {
        exclude group: "org.antlr"
    }
    library ("org.jgrapht:jgrapht-io:${project.jgraphtVersion}") {
        exclude group: "org.antlr"
    }

    testRuntimeOnly "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${project.jacksonDataFormatYamlVersion}"
    testRuntimeOnly "com.fasterxml.jackson.core:jackson-databind:${project.jacksonDatabindVersion}"

    contained("org.jgrapht:jgrapht-core:${project.jgraphtVersion}") {
        jarJar.pin(it, project.jgraphtVersion)
        jarJar.ranged(it, project.opc.buildSupportedVersionRange(project.jgraphtVersion))
        exclude group: "org.antlr"
    }
    contained("org.jgrapht:jgrapht-ext:${project.jgraphtVersion}") {
        jarJar.pin(it, project.jgraphtVersion)
        jarJar.ranged(it, project.opc.buildSupportedVersionRange(project.jgraphtVersion))
        exclude group: "org.antlr"
    }
    contained("org.jgrapht:jgrapht-io:${project.jgraphtVersion}") {
        jarJar.pin(it, project.jgraphtVersion)
        jarJar.ranged(it, project.opc.buildSupportedVersionRange(project.jgraphtVersion))
        exclude group: "org.antlr"
    }

    // Locally sourced extra mods for runtime (i.e. testing)
    for (extraModJar in fileTree(dir: extraModsDir, include: '*.jar')) {
        def basename = extraModJar.name.substring(0, extraModJar.name.length() - ".jar".length())
        def versionSep = basename.lastIndexOf('-')
        assert versionSep != -1
        def artifactId = basename.substring(0, versionSep)
        def version = basename.substring(versionSep + 1)
        runtimeOnly fg.deobf("extra-mods:$artifactId:$version")
    }
}
