name: Feature Request
description: If you have something new you would like to add
labels: ["Feature: Request"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if an issue already exists for your feature request.
      options:
        - label: I have searched the existing feature requests.
          required: true
  - type: checkboxes
    attributes:
      label: Are you using the latest Aequivaleo Version?
      description: |
        Please check to see if any newer version fixes the issue you're experiencing.
        [List of all Aequivaleo versions](https://www.curseforge.com/minecraft/mc-mods/aequivaleo/files/all)
      options:
        - label: |
            I am running the latest **beta/release** version of Aequivaleo for my Minecraft version.
            I am also running the latest versions of other mods that are part of my problem.
          required: true
  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft Version
      options: ["1.20", "1.21"]
    validations:
      required: true
  - type: input
    attributes:
      label: Aequivaleo Version
      description: Exact Aequivaleo version either from file name or in-game mod list.
      placeholder: 1.xx.xx-XXXX
  - type: textarea
    attributes:
      label: Related Mods and their Versions
      description: "Mods that may interact with the recipes in your feature request."
      placeholder: |
        1. Forge Version:
        2. Aequivaleo Version:
        3. ....
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: "A clear and concise description of what the problem is. Ex: I'm always frustrated when..."
  - type: textarea
    attributes:
      label: Feature description
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking any text area to highlight it and then dragging files in.
  - type: textarea
    attributes:
      label: "Footer"
      description: This is issue footer. Please leave this text as is.
      value: |
        ---
        ## Viewers
        * Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
        * Add a comment if you have any insights or background information that isn't already part of the conversation.
    validations:
      required: true