name: Release

on:
  push:
    branches:
      - "version/*"
      - "release/*"

permissions:
  contents: write
  statuses: write

jobs:
  release:
    uses: ldtteam/operapublicacreator/.github/workflows/gradle.publish.yaml@main
    with:
      java: 17
      curse_release_type: ${{ contains(github.ref, 'release') && 'release' || 'beta' }}
    secrets: inherit
